import ModalProvider from "@/providers/ModalProvider";
import { ClerkProvider } from "@clerk/nextjs";

import "@/sass/main.scss";
import { ReduxProvider } from "@/store/provider";
import { quicksand } from "./font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={quicksand.className}>
        <body>
          <ReduxProvider>
            <ModalProvider />
            {children}
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
