POST http://localhost:3000/api/blurb-requests
Content-Type: application/json

{
  "platformIds": [1, 2, 3],
  "blurbRequest": {
    "brandName": "P@CMU's podcast - The breakdown | Product and Entrepreneurship",
    "theme": "how to make the most of your summer internship",
    "description": "topics corvered: Setting expectations for the internship,How to network during the internship, How to maximize your experience",
    "links": "Spotify, Youtube",
    "targetAudience": "university students seeking internship or on an internship",
    "includeEmojis": true,
    "includeHashtags": true
  }
}