import "@/sass/main.scss";

export const metadata = {
  title: "Generate Blurb",
  description: "Generated by provide customized blurb",
};

export default function GenerateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
